FROM node:22-alpine AS build

ARG VITE_API_URL
ARG VITE_MAP_STYLE_URL
ENV VITE_API_URL=${VITE_API_URL}
ENV VITE_MAP_STYLE_URL=${VITE_MAP_STYLE_URL}

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:1.27-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 8080
